services:
  redis:
    image: redis:alpine
    container_name: cache_store_redis_redis_cache
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 10s
      timeout: 3s

  gem:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUNDLE_SAGEONEGEMS__JFROG__IO
    image: sageone/cache_store_redis
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - BUNDLE_SAGEONEGEMS__JFROG__IO
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/usr/src/app
